# Eth2 API endpoint
eth2_api: http://mainnet-lodestar-520_beacon_node_1:9596

# Optional graffiti to display in your JSON response
ws_server_graffiti: 

# Hostname for Redis server
redis: redis

# uwsgi server configuration
uwsgi:
  wsgi: ws_server:app
  http: 0.0.0.0:8081
  http-timeout: 3000
  processes: 1
  threads: 1
