version: "3.3"

services:
  redis:
    image: "redis"
    ports:
      - 6379
    networks:
      - ws_network
  eth2_ws_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: "eth2_ws_server"
    networks:
      - ws_network
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - "0.0.0.0:8081:8081"

networks:
  # NOTE: this assumes that the user has already greated the ws_network and has also confiured the lodestar docker-compose.yml to use the same network
  ws_network:
    external: true