version: "3.3"

services:
  redis:
    image: "redis"
    ports:
      - 6379
  eth2_ws_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: "eth2_ws_server"
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "0.0.0.0:80:80"

# Uncomment the below section to use a pre-existing docker network
# networks:
#   default:
#     external:
#       # Enter the name of the pre-existing docker network you want to use
#       name: "bridge"
